---
services:
  komga-meta-manager:
    image: simonverbois/komga-meta-manager:latest
    container_name: komga-meta-manager
    restart: no
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ./config:/config
