# Testing compose

---
services:
  komga-meta-manager:
    build: .
    container_name: komga-meta-manager
    restart: no
    environment:
      - TZ=Europe/Brussels
      - KMM_KOMGA_API_KEY=${KMM_KOMGA_API_KEY:-}
      - KMM_DEEPL_API_KEY=${KMM_DEEPL_API_KEY:-}
    volumes:
      - ./config:/config
    command: sh -c "python -m modules.main"
