name: Build and push to internal registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to internal registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.LOCAL_GITEA_URL }}
          username: ${{ secrets.LOCAL_GITEA_REGISTRY_USER }}
          password: ${{ secrets.LOCAL_GITEA_REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.LOCAL_GITEA_URL }}/simonverbois/komga-meta-manager:latest
            ${{ vars.LOCAL_GITEA_URL }}/simonverbois/komga-meta-manager:${{ gitea.sha }}
